Vagrant.configure("2") do |config|
 config.vm.define :clienteUbuntu do |clienteUbuntu|
 clienteUbuntu.vm.box = "bento/ubuntu-20.04"
 clienteUbuntu.vm.network :private_network, ip: "192.168.100.4"
 clienteUbuntu.vm.hostname = "clienteUbuntu"
 end
 config.vm.define :servidorUbuntu do |servidorUbuntu|
 servidorUbuntu.vm.box = "bento/ubuntu-20.04"
 servidorUbuntu.vm.network :private_network, ip: "192.168.100.5"
 servidorUbuntu.vm.provision "shell", path: "script.sh"
 servidorUbuntu.vm.hostname = "servidorUbuntu"
 end
end