# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define :server1 do |server1_config|
      server1_config.vm.provider :virtualbox do |vb_config|
          vb_config.name = "server1"
      end
      server1_config.vm.hostname = "server1"
      server1_config.vm.network "private_network", ip: "192.162.100.10"
      server1_config.vm.provision :shell, path: "web1.sh"
  end

  config.vm.define :server2 do |server2_config|
      server2_config.vm.provider :virtualbox do |vb_config|
          vb_config.name = "server2"
      end
      server2_config.vm.hostname = "server2"
      server2_config.vm.network "private_network", ip: "192.162.100.11"
      server2_config.vm.provision :shell, path: "web2.sh"
  end

  config.vm.define :haproxy do |haproxy_config|
      haproxy_config.vm.provider :virtualbox do |vb_config|
          vb_config.name = "haproxy"
      end
      haproxy_config.vm.hostname = "haproxy"
      haproxy_config.vm.network :forwarded_port, guest: 80, host: 8080
      haproxy_config.vm.network "private_network", ip: "192.162.100.12"
      haproxy_config.vm.provision :shell, path: "Haproxy.sh"
  end
end
